services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./LaravelApp:/var/www/html
    ports:
      - 9000:80
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1234
  
  mysql_db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Laravel_db
      MYSQL_ROOT_USER: root
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1

 # Redis Server
  redis:
      image: redis:alpine
      restart: always
      ports:
            - "6379:6379"
      command: redis-server --save 20 1 --loglevel warning --requirepass "1234"
      volumes:
        - cache:/data

volumes:
  cache:
    driver: local